test:
	${MAKE} -C lint-diff-test test
	${MAKE} -C sort-directory-order-test test
	${MAKE} -C git-clone-related-test test

clean:
	${MAKE} -C lint-diff-test clean
	${MAKE} -C sort-directory-order-test clean
	${MAKE} -C git-clone-related-test clean
