version: "3"

services:
    client:
        build:
          context: ./app 
          dockerfile: Dockerfile
        ports:
            - 3000:3000
    server:
        build:
          context: ./server-app 
          dockerfile: Dockerfile
        ports:
            - 8080:8080
        volumes:
            - ./Experiment:/usr/src/app/Experiment
